
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kazwfyuwlvkcntphcxsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthendmeXV3bHZrY250cGhjeHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjMxODYsImV4cCI6MjA2NDUzOTE4Nn0.ZBrm3aGVY5_ZQYeKVFyfVudrdpLqJAatfnFtrC4O75g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
